version: 2

# Reference and docs for this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

updates:
  # group cargo deps into a single monthly PR
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build:"
    groups:
      deps:
        patterns: 
          - "*"
        exclude-patterns:
          - "clap_mangen"
           
      # flakey or problematic deps are still submitted individually
      clap_mangen:
        patterns:
          - "clap_mangen"

  # group GH actions deps into a single monthly PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build:"
    groups:
      actions-deps:
        patterns: 
          - "*"
