[package]
authors = ["Waleed Khan <me@waleedkhan.name>"]
description = "Support library for git-branchless."
edition = "2021"
keywords = ["git"]
license = "GPL-2.0-only"
name = "git-branchless-lib"
repository = "https://github.com/arxanas/git-branchless"
rust-version = "1.56.0"
version = "0.3.12"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "branchless"

[features]
default = []
integration-test-bin = []

[[bench]]
harness = false
name = "benches"

## Testing binaries ##
[[bin]]
name = "git-branchless-regression-test-cherry-pick"
path = "bin/testing/regression_test_cherry_pick.rs"
required-features = ["integration-test-bin"]
test = true

[[bin]]
name = "git-branchless-profile-changed-paths"
path = "bin/testing/profile_changed_paths.rs"
required-features = ["integration-test-bin"]
test = true

[dependencies]
anyhow = "1.0.57"
assert_cmd = "2.0.4"
chashmap = "2.2.2"
chrono = "0.4.19"
color-eyre = "0.6.1"
concolor = { version = "0.0.8", features = ["auto"] }
console = "0.15.0"
cursive = { version = "0.18.0", default-features = false }
eden_dag = { package = "esl01-dag", version = "0.2.1" }
eyre = "0.6.8"
git2 = { version = "0.14.2", default-features = false }
git-record = { version = "0.1", path = "../git-record" }
indicatif = "0.17.0-rc.10"
itertools = "0.10.3"
lazy_static = "1.4.0"
os_str_bytes = "6.0.0"
rayon = "1.5.3"
regex = "1.5.5"
rusqlite = { version = "0.27.0", features = ["bundled"] }
tempfile = "3.3.0"
textwrap = "0.15.0"
tracing = "0.1.34"
tracing-chrome = "0.6.0"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
insta = "1.14.0"
lazy_static = "1.4.0"
portable-pty = "0.7.0"
vt100 = "0.15.1"
